name: main_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_it: ^7.6.2
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.3
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1
  oauth2: ^2.0.2
  dio: ^5.3.2
  retrofit: ^4.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  injectable: ^2.3.0
  logger: ^2.0.1
  alice: ^0.3.3
  keyboard_service: ^2.0.2
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^14.1.3+1
  tap_debouncer: ^2.2.0
  event_bus: ^2.0.0
  fluttertoast: ^8.2.2

  suga_core:
    git:
      url: https://github.com/duc1205/suga_core
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  retrofit_generator: ^7.0.8
  flutter_gen_runner: ^5.3.1
  
flutter_gen:
  output: lib/gen/
  line_length: 150
  
flutter:
  uses-material-design: true
  assets:
    - resources/langs/
    - resources/images/
    - resources/icons/

